force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Store and manage individual job applications.
It needs to associate with contacts, track scheduled interviews, maintain notes, manage tasks, and provide functionality to send emails directly from the record.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the job application as a candidate moves through the process.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
/*
*********************************************************
Apex Class Name    : TestDataFactory
Created Date       : July 2024
@description       : This test data factory can be used to simplify testing logic
@author            : Steven Trumble
*********************************************************
*/
@isTest
public class TestDataFactory {

/*
*********************************************************
@Method Name    : createJobApplicationsWithStatus
@author         : Steven Trumble
@description    : method to is used to create Job Application(s) with a specific Status__c
@param          : Integer - numJobApplications - number of job applications that need tasks created
                    String - status - the Job_Application__c.Status__c 
@return         : List of inserted Job Applications
********************************************************
*/    
    public static List<Job_Application__c> createJobApplicationsWithStatus(Integer numJobApplications, String status) {
        List<Job_Application__c> jobApplications = new List<Job_Application__c>();
        for (Integer i = 0; i < numJobApplications; i++){
            Job_Application__c jobApplication = new Job_Application__c(Status__c = status);
            jobApplications.add(jobApplication);
        }
        insert jobApplications;
        return jobApplications;
    }
}