force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Store and manage individual job applications.
It needs to associate with contacts, track scheduled interviews, maintain notes, manage tasks, and provide functionality to send emails directly from the record.</description>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>Expected salary for the job position</description>
    <inlineHelpText>Expected salary for the job position</inlineHelpText>
    <label>Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the job application as a candidate moves through the process.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationTriggerHandler.cls
/*
*********************************************************
Apex Class Name    : JobApplicationTriggerHandler
Created Date       : July 2024
@description       : This trigger handler calls various methods in JobApplicationUtility and SalaryCalculator based on the running context
@author            : Steven Trumble
*********************************************************
*/

public with sharing class JobApplicationTriggerHandler extends TriggerHandler {
    public override void beforeInsert() {
        if (!isBypassed('beforeInsert')) {
            JobApplicationUtility.setPrimaryContact(Trigger.new);
            List<Job_Application__c> jobAppsWithSalary = getJobAppsWithSalary(Trigger.new);
            if (!jobAppsWithSalary.isEmpty()) {
                SalaryCalculator.calculateTaxesAndTakeHomePay(jobAppsWithSalary);
            }
        }
    }

    public override void beforeUpdate() {
        if (!isBypassed('beforeUpdate')) {
            JobApplicationUtility.setPrimaryContact(Trigger.new);
            List<Job_Application__c> jobAppsWithSalary = getJobAppsWithSalary(Trigger.new);
            if (!jobAppsWithSalary.isEmpty()) {
                SalaryCalculator.calculateTaxesAndTakeHomePay(jobAppsWithSalary);
            }
        }
    }
    
    public override void afterInsert() {
        if (!isBypassed('afterInsert')) {
            JobApplicationUtility.createJobApplicationTasks(Trigger.new);
        }
    }

    public override void afterUpdate() {
        if (!isBypassed('afterUpdate')) {
            List<Job_Application__c> jobAppsChangedStatus = getJobAppsWithChangedStatus(Trigger.new, Trigger.oldMap);
            if (!jobAppsChangedStatus.isEmpty()) {
                JobApplicationUtility.createJobApplicationTasks(jobAppsChangedStatus);
            }
        }
    }

    private List<Job_Application__c> getJobAppsWithSalary(List<Job_Application__c> jobApps) {
        List<Job_Application__c> jobAppsWithSalary = new List<Job_Application__c>();
        for (Job_Application__c jobApp : jobApps) {
            if (jobApp.Salary__c != null) {
                jobAppsWithSalary.add(jobApp);
            }
        }
        return jobAppsWithSalary;
    }

    private List<Job_Application__c> getJobAppsWithChangedStatus(List<SObject> newSObjects, Map<Id, SObject> oldSObjectsMap) {
        List<Job_Application__c> jobAppsChangedStatus = new List<Job_Application__c>();
        for (SObject newSObj : newSObjects) {
            Job_Application__c newJobApp = (Job_Application__c)newSObj;
            Job_Application__c oldJobApp = (Job_Application__c)oldSObjectsMap.get(newJobApp.Id);
            if (newJobApp.Status__c != oldJobApp.Status__c) {
                jobAppsChangedStatus.add(newJobApp);
            }
        }
        return jobAppsChangedStatus;
    }
}